### ISSUE TITLE
when project is selected we lose the red navigation highlight

### ISSUE THREAD

**Issue by denten** [xpmethod/xpmethod.github.io#186]
This is regression introduced by the new CSS. No big deal.

**Comment by nyutka** [comment]
@denten how do yo identify that a post is a project? By the fact that it's inside _posts/projects folder?

**Comment by denten** [comment]
Jekyll parses everything in the _post directory, regardless of the sub-directory. If you look at the template, we are displaying the yaml category corresponding to the research group name (so knowledge-design-studio, literary-modeling-and-visualization and so on). layout: project is also available through the api. Come to think of it, why does the highlight work for events but not for projects??

**Comment by nyutka** [comment]
Cause current logic checks if there is the menu title in url, i.e. it works for the posts which have `category: projects` in yaml, i.e. http://localhost:4000/projects/literary-modeling.html, but not for everything else, i.e. http://localhost:4000/literary-modeling-and-visualization-lab/creative-ai.html

**Comment by nyutka** [comment]
there are currently two solutions I came to. first one I can check if there is word `projects` in the file path of current post, i.e. for http://localhost:4000/literary-modeling-and-visualization-lab/creative-ai.html it will be `_posts/projects/2018-02-01-creative-ai.md`, and that's why I asked, if, from human point of view, only posts inside  projects folder are projects?

The other solution is little harder to code, but the idea is to check if the post has a category (for example `category: literary-modeling-and-visualization-lab`), we find another post which has a title equal to that category, and if that root level post has `category: projects` in yaml, then we mark that the current post is also a project.

**Comment by denten** [comment]
Checking for projects/ is fine as long as we don't lose the ability to build on GitHub servers. Currently we push the sources without building locally.

**Comment by nyutka** [comment]
Do you get the pull request?

**Comment by nyutka** [comment]
it's because the Travis failed building, as we have some errors. I have fixed one issue and send you PR. 

Also it can not find some images like roma-project.png, /wax_screen.gif

**Comment by denten** [comment]
Working now.
